/* Main.c file generated by New Project wizard
 *
 * Created:   Sun May 10 2026
 * Processor: LPC2138
 * Compiler:  GCC for ARM
 */

// ================= LCD =================
#include <lpc213x.h>

// ================= INPUTS (Port 0 Buttons - Active Low) =================
#define BTN_PWR  (1<<0)  // P0.0
#define BTN_PLAY (1<<1)  // P0.1
#define BTN_NEXT (1<<2)  // P0.2
#define BTN_PREV (1<<3)  // P0.3
#define BTN_VOLP (1<<4)  // P0.4
#define BTN_VOLM (1<<5)  // P0.5
#define BTN_MODE (1<<6)  // P0.6

// ================= OUTPUTS (Port 0) =====================================
#define LED_R    (1<<7)  // P0.7
#define LED_G    (1<<8)  // P0.8
#define LED_Y    (1<<9)  // P0.9 (Replaced Blue with Yellow)
#define BUZZER   (1<<16) // P0.16

// ================= LCD OUTPUTS (Port 1) =================================
#define LCD_RS   (1<<16) // P1.16
#define LCD_EN   (1<<18) // P1.18

// ================= GLOBAL VARIABLES =====================================
int power_state; 
int play_state;  
int track_idx;   
int volume;      
int music_mode;  
int scroll_index;
int scroll_timer;    

// ================= FUNCTION PROTOTYPES ==================================
void pll_init(void);
void delay_ms(unsigned int ms);
void lcd_init(void);
void cmd(unsigned char a);
void dat(unsigned char b);
void show(char *s);
void update_lcd_display(void);

// ================= MAIN =================================================
int main()
{
    // Variable Initialization
    power_state = 0;
    play_state = 0;
    track_idx = 0; 
    volume = 5;    
    music_mode = 0;
    scroll_index = 0;
    scroll_timer = 0;

    // Previous button states for Edge Detection (1 means unpressed, 0 means pressed)
    int pwr_prev=1, play_prev=1, next_prev=1, prev_prev=1;
    int volp_prev=1, volm_prev=1, mode_prev=1;

    pll_init();
    VPBDIV = 0x01; 

    // --- Configure Port Directions ---
    IO0DIR |= LED_R | LED_G | LED_Y | BUZZER;
    IO0DIR &= ~(BTN_PWR | BTN_PLAY | BTN_NEXT | BTN_PREV | BTN_VOLP | BTN_VOLM | BTN_MODE);
    IO1DIR |= LCD_RS | LCD_EN | 0xFF000000; 

    lcd_init();

    // --- Set Initial LED State to RED (System Off) ---
    IO0SET = LED_R;
    IO0CLR = LED_G | LED_Y | BUZZER;

    while(1)
    {
        // 1. Read the CURRENT state of all buttons (1 = Not Pressed, 0 = Pressed)
        int pwr_curr  = (IO0PIN & BTN_PWR)  ? 1 : 0;
        int play_curr = (IO0PIN & BTN_PLAY) ? 1 : 0;
        int next_curr = (IO0PIN & BTN_NEXT) ? 1 : 0;
        int prev_curr = (IO0PIN & BTN_PREV) ? 1 : 0;
        int volp_curr = (IO0PIN & BTN_VOLP) ? 1 : 0;
        int volm_curr = (IO0PIN & BTN_VOLM) ? 1 : 0;
        int mode_curr = (IO0PIN & BTN_MODE) ? 1 : 0;

        // ---- POWER BUTTON ----
        if (pwr_prev == 1 && pwr_curr == 0) {
            power_state = !power_state;
            
            // --- NEW: 2-Second Buzzer on System ON/OFF ---
            IO0SET = BUZZER;
            delay_ms(2000); 
            IO0CLR = BUZZER;

            if(power_state == 0) {
                play_state = 0; 
                
                // SYSTEM OFF -> RED LED ON
                IO0SET = LED_R; 
                IO0CLR = LED_G | LED_Y; 
                
                cmd(0x01); // Clear LCD
            }
        }

        // ---- SYSTEM ACTIVE LOGIC ----
        if(power_state == 1) 
        {
            // Play/Pause
            if (play_prev == 1 && play_curr == 0) {
                play_state = !play_state;
                // No beep needed here, handled by the continuous logic below
            }
            
            // Next Track
            if (next_prev == 1 && next_curr == 0) {
                if(track_idx < 2) track_idx++;
            }
            
            // Previous Track
            if (prev_prev == 1 && prev_curr == 0) {
                if(track_idx > 0) track_idx--;
            }
            
            // Volume Up 
            if (volp_prev == 1 && volp_curr == 0) {
                if(volume < 10) volume++; 
            }
            
            // Volume Down 
            if (volm_prev == 1 && volm_curr == 0) {
                if(volume > 1) volume--;
            }
            
            // Mode Change
            if (mode_prev == 1 && mode_curr == 0) {
                music_mode++;
                if(music_mode > 2) music_mode = 0;
            }

            // --- NEW: Update Discrete LED and Continuous Buzzer State ---
            if(play_state == 1) { 
                IO0SET = LED_G; 
                IO0SET = BUZZER;        // PLAYING -> GREEN ON, BUZZER ON CONTINUOUSLY
                IO0CLR = LED_R | LED_Y; 
            } else { 
                IO0SET = LED_Y; 
                IO0CLR = LED_R | LED_G; // PAUSED -> YELLOW ON
                IO0CLR = BUZZER;        // PAUSED -> BUZZER OFF
            }

            // --- Update Screen ---
            update_lcd_display();
        }
        else 
        {
            // ---- SYSTEM OFF LOGIC ----
            IO0CLR = BUZZER; // Failsafe to ensure buzzer is off when system is dead
            cmd(0x80);
            show("  SYSTEM OFF    ");
            cmd(0xC0);
            show("                ");
        }
        
        // 2. Save current states as the "previous" state for the next loop iteration
        pwr_prev = pwr_curr;
        play_prev = play_curr;
        next_prev = next_curr;
        prev_prev = prev_curr;
        volp_prev = volp_curr;
        volm_prev = volm_curr;
        mode_prev = mode_curr;

        // Scroll speed controller
        scroll_timer++;
        if(scroll_timer >= 50) { 
            if(play_state == 1) {
                scroll_index++;
                if(scroll_index >= 61) scroll_index = 0; 
            }
            scroll_timer = 0;
        }

        delay_ms(5); // Tiny delay just to keep Proteus stable
    }
}

// ================= CUSTOM DISPLAY FUNCTION ==================================
void update_lcd_display() 
{
    char line1[17];
    int i;
    int char_pos;
    const char *current_msg; 
    
    line1[0] = 'T'; line1[1] = 'r'; line1[2] = 'k'; line1[3] = ':'; line1[4] = ' ';
    line1[5] = 'A' + track_idx; 
    line1[6] = ' '; line1[7] = ' '; 
    line1[8] = 'V'; line1[9] = 'o'; line1[10] = 'l'; line1[11] = ':'; line1[12] = ' ';
    
    if(volume == 10) {
        line1[13] = '1';
        line1[14] = '0';
    } else {
        line1[13] = '0';
        line1[14] = volume + '0';
    }
    line1[15] = ' ';
    line1[16] = '\0'; 

    cmd(0x80);
    show(line1);

    cmd(0xC0);
    if(play_state == 1) {
        if(music_mode == 0) current_msg = "    [PLAY] MODE: POP - Now Playing: Your Favorite Song...    ";
        else if(music_mode == 1) current_msg = "    [PLAY] MODE: ROCK - Now Playing: Your Favorite Song...   ";
        else current_msg = "    [PLAY] MODE: JAZZ - Now Playing: Your Favorite Song...   ";

        for (i = 0; i < 16; i++) {
            char_pos = (scroll_index + i) % 61;
            dat(current_msg[char_pos]);
        }
    } else {
        if(music_mode == 0) show("[PAUS] MODE: POP ");
        if(music_mode == 1) show("[PAUS] MODE: ROCK");
        if(music_mode == 2) show("[PAUS] MODE: JAZZ");
    }
}

// ================= HARDWARE FUNCTIONS =======================================

void delay_ms(unsigned int ms)
{
    unsigned int i, j;
    for(i=0; i<ms; i++)
        for(j=0; j<3000; j++); 
}

// ================= LCD FUNCTIONS ============================================

void lcd_init()
{
    delay_ms(20);
    cmd(0x38); // 8-bit mode, 2 lines
    cmd(0x0C); // Display ON, Cursor OFF
    cmd(0x01); // Clear Display
    delay_ms(5);
    cmd(0x06); // Auto Increment cursor
    cmd(0x80); // Move to Row 1 Col 1
}

void cmd(unsigned char a)
{
    IO1CLR = 0xFF000000; 
    IO1SET = ((unsigned long)a << 24); 

    IO1CLR = LCD_RS; 
    IO1SET = LCD_EN; 
    delay_ms(2);
    IO1CLR = LCD_EN; 
}

void dat(unsigned char b)
{
    IO1CLR = 0xFF000000; 
    IO1SET = ((unsigned long)b << 24); 

    IO1SET = LCD_RS; 
    IO1SET = LCD_EN; 
    delay_ms(2);
    IO1CLR = LCD_EN; 
}

void show(char *s)
{
    while(*s) {
        dat(*s++);
    }
}

// ================= PLL CONFIGURATION ========================================

void pll_init(void)
{
    PLLCFG  = 0x24;
    PLLCON  = 0x01;
    PLLFEED = 0xAA;
    PLLFEED = 0x55;

    while (!(PLLSTAT & (1<<10))); 

    PLLCON  = 0x03;
    PLLFEED = 0xAA;
    PLLFEED = 0x55;
}